##1. 데이터 불러오기 및 전처리

In [ ]:
!unzip -qq '/content/drive/MyDrive/BITAmin/2024 fall project nlp/TL_01._KAKAO(1).zip'

In [ ]:
# josn 데이터 여러 개 불러오기
import os
import json

path = '/content'

# 경로 내에 파일을 모두 불러옴
file_list = os.listdir(path)

# json 확장자를 가진 파일로 새로운 리스트 생성
json_file_list = [file for file in file_list if file.endswith('.json')]

# josn_file_list에는 json 파일들만 남아있게 된다.

In [ ]:
json_file_list

[]

In [ ]:
import json
import os

df = []  # 데이터를 저장할 리스트 생성
error_files = []  # 오류가 발생한 파일을 저장할 리스트

# json 파일을 하나씩 읽어서 리스트에 추가
for json_file in json_file_list:
    file_path = os.path.join(path, json_file)  # 파일의 전체 경로
    try:
        with open(file_path, "r", encoding="utf-8") as f:  # 인코딩 명시
            data = json.load(f)  # json 데이터 읽어오기  # 각 json 데이터를 리스트에 추가
            for info in data['info']:
               subject = info['annotations']['subject']
               speaker_type = info['annotations']['speaker_type']
               text = info['annotations']['text']
               df.append({'subject': subject, 'speaker_type': speaker_type, 'text': text})
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON in file: {json_file} - {e}")
        error_files.append(json_file)  # 오류 발생 파일 리스트에 추가
    except Exception as e:
        print(f"Unexpected error in file: {json_file} - {e}")
        error_files.append(json_file)

if error_files:
    print("Files with errors:", error_files)


Error decoding JSON in file: KAKAO_1648_13.json - Expecting value: line 137 column 25 (char 4950)
Files with errors: ['KAKAO_1648_13.json']


In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(df)

In [ ]:
df

subject speaker_type                                               text
0      스포츠/레저       다자간 대화  1 : 근데 나 산책 다닐 때 보면 남자랑은 여자랑 진짜 다른 게 느껴지는데\n1 ...
1      주거와 생활       다자간 대화  1 : 흠 자취하면 좋은점이 뭐야?\n2 : 그러게 나도 자취하고 싶은데 궁금하다 ...
2          게임          1:1  1 : 니는 어릴 때 오락실 자주 갔었나? 키키\n2 : 나 중딩 때 오락실 자주 ...
3          게임          1:1  1 : 키키 ** 혹시 부루마블 같은 거 보드게임은 좀 해봐썽?\n2 : 웅 그것도...
4          교육          1:1  1 : 학생 때가 그립당 맞지?\n2 : 그치 지금 생각 해보면 아무 생각 없이 학...
...       ...          ...                                                ...
17994  상거래 전반          1:1  1 : 너 혹시 주식해? 키키\n1 : 좀 전에 확인했다가 좌절...\n2 : 키키...
17995      여행          1:1  1 : 제주도 갔을 때 숙소랑 경로 다 알아보고 갔어?\n2 : 다 알아봤지 하하 ...
17996   연애/결혼          1:1  1 : 너 지금 연애 중이야?\n2 : 아니 나는 아직 혼자야 ㅠㅠ\n1 : 오 동...
17997  스포츠/레저       다자간 대화  1 : 우리 햄스터 말고 등산 가서 다람쥐 구경하자\n2 : 담 주에 최고 온도 1...
17998   방송/연예       다자간 대화  1 : 요즘 엠넷 스트리트 우먼 파이터를 열심히 보고 있어~\n1 : 연기자가 아닌...

[17999 rows x 3 columns]

In [ ]:
df.loc[0, 'text']

'1 : 근데 나 산책 다닐 때 보면 남자랑은 여자랑 진짜 다른 게 느껴지는데\n1 : 춥거나 덥거나 상관없이 축구나 농구를 하고 있는 모습을 보면 그래\n2 : 맞앙\n2 : 그리고 확실히 남자들이 몸에 열이 많은 거 같음\n3 : 나 이사 오고 1년 넘게 몰랐는데 우리 동네에도 주말에 축구 하는 사람들 있더라\n1 : 키키 오 벌써 1년이나 됐어?\n1 : 시간 빠르네\n1 : 마져\n1 : 무슨 공원에 축구장 조그마한 거 있음 사람들 다 이용해\n2 : 난 구기 종목 할 줄 아는 거 볼링밖에 없엉 키키\n3 : 키키 볼링도 진짜 진짜 가끔 하는 거여서 하고 다음날 되면 골반 완전 아픔\n1 : ㅋㄱ 나는 이상하게 손가락이랑 손목 위 팔등?\n1 : 거기가 아파\n2 : 취중 볼링이 얼마나 재밌게 고통도 안 느껴져 키키\n3 : 알지\n3 : 수면 마취보다 강하다는 알콜 마취 키키\n1 : 헐 나랑 술 마시고 볼링 치러 가 줘\n1 : 넘 재밌겠다\n1 : 부끄럽지도 않겠네\n2 : 그랭 키키\n2 : 혹시 락 볼링장 가 봤어?\n3 : 아 거기 술마시고 가서 치면 대존잼\n1 : 난 항상 가는 곳마다 락볼링장이었어\n2 : 오호 근데 락볼링장이 더 비싸서 화나\n3 : 마자\n3 : 근데 오랜만에 볼링 치고 싶긴 하다\n1 : 너희 실력은 어때\n1 : 나는 꽝꽝 내리찍는 거 선수\n2 : 난 또랑 신인데 가끔 운 좋으면 좀 치는? 키키\n3 : 나도 운 좋으면 그나마 괜찮은 정도 키키\n3 : 우리 다음에 같이 치러 가자 콜!'

In [ ]:
annotations

0        {'subject': '반려동물', 'speaker_type': '1:1', 'si...
1        {'subject': '건강', 'speaker_type': '1:1', 'size...
2        {'subject': '반려동물', 'speaker_type': '다자간 대화', ...
3        {'subject': '식음료', 'speaker_type': '다자간 대화', '...
4        {'subject': '사회이슈', 'speaker_type': '1:1', 'si...
                               ...                        
17994    {'subject': '군대', 'speaker_type': '1:1', 'size...
17995    {'subject': '교통', 'speaker_type': '다자간 대화', 's...
17996    {'subject': '타 국가 이슈', 'speaker_type': '다자간 대화...
17997    {'subject': '군대', 'speaker_type': '다자간 대화', 's...
17998    {'subject': '군대', 'speaker_type': '1:1', 'size...
Name: annotations, Length: 17999, dtype: object

## 10/28. 기준 재시작 ^^

In [ ]:
import tensorflow as tf
import torch

from transformers import BertTokenizer
from transformers import BertForSequenceClassification, AdamW, BertConfig
from transformers import get_linear_schedule_with_warmup
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import random
import time
import datetime

In [ ]:
n_devices = torch.cuda.device_count()
print(n_devices)

for i in range(n_devices):
    print(torch.cuda.get_device_name(i))

## 2. roberta 모델 불러오기

In [ ]:

!pip install transformers

In [ ]:

import os
import random
from tqdm import tqdm

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from transformers import TrainingArguments, Trainer
from transformers import AutoModelForSequenceClassification, AutoConfig, AutoTokenizer


In [ ]:
from transformers import AutoModel, AutoTokenizer

model = AutoModel.from_pretrained("klue/roberta-base")
tokenizer = AutoTokenizer.from_pretrained("klue/roberta-base")


Some weights of RobertaModel were not initialized from the model checkpoint at klue/roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [ ]:

import urllib.request
from sklearn import preprocessing
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

In [ ]:
config = AutoConfig.from_pretrained('klue/roberta-large')
config.num_labels = 3

model = AutoModelForSequenceClassification.from_pretrained('klue/roberta-large', config=config)

config.json:   0%|          | 0.00/547 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.35G [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at klue/roberta-large and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.optimizers import Adam


# 예측 변수와 설명 변수 분리
X = df['text']  # 대화 내용
y = df['subject']  # 주제

# Label Encoding for the target variable
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# 학습 데이터와 테스트 데이터 분리 (80:20 비율)
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# 데이터 토큰화
def tokenize_data(texts, tokenizer, max_length=128):
    return tokenizer(
        list(texts),
        padding=True,
        truncation=True,
        max_length=max_length,
        return_tensors="tf"
    )

X_train_tokenized = tokenize_data(X_train, tokenizer)
X_test_tokenized = tokenize_data(X_test, tokenizer)


In [ ]:
X_train_tokenized

{'input_ids': <tf.Tensor: shape=(14399, 128), dtype=int32, numpy=
array([[   0,   21,   30, ..., 2116, 4258,    2],
       [   0,   21,   30, ..., 1507,  885,    2],
       [   0,   21,   30, ..., 2098, 2052,    2],
       ...,
       [   0,   21,   30, ..., 2259, 1097,    2],
       [   0,   21,   30, ..., 3780, 1537,    2],
       [   0,   21,   30, ...,   22,   30,    2]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(14399, 128), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(14399, 128), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)>}